# Generated by Django 4.1.3 on 2024-08-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HkDailyPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('trade_date', models.DateField()),
                ('volume', models.IntegerField()),
                ('turnover_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HkQfqFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('trade_date', models.DateField()),
                ('factor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StockHkList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('hkcs1', models.CharField(max_length=100)),
                ('indices', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=100)),
                ('ak_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StockUsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('gics1', models.CharField(max_length=100)),
                ('gics2', models.CharField(max_length=100)),
                ('indices', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsDailyPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('trade_date', models.DateField()),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('volume', models.IntegerField()),
                ('turnover_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UsQfqFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('trade_date', models.DateField()),
                ('factor', models.FloatField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='usqfqfactor',
            constraint=models.UniqueConstraint(fields=('code', 'trade_date'), name='us_qfq_code_date'),
        ),
        migrations.AddConstraint(
            model_name='usdailyprices',
            constraint=models.UniqueConstraint(fields=('code', 'trade_date'), name='us_day_price_code_date'),
        ),
        migrations.AddConstraint(
            model_name='hkqfqfactor',
            constraint=models.UniqueConstraint(fields=('code', 'trade_date'), name='hk_qfq_code_date'),
        ),
        migrations.AddConstraint(
            model_name='hkdailyprices',
            constraint=models.UniqueConstraint(fields=('code', 'trade_date'), name='hk_day_price_code_date'),
        ),
    ]
