# Generated by Django 4.1.3 on 2024-08-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockDailyPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('exchange', models.CharField(max_length=40)),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('trade_date', models.DateField()),
                ('volume', models.IntegerField()),
                ('fq_type', models.CharField(default='qfq', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='StockHkList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('hkcs1', models.CharField(max_length=100)),
                ('indices', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StockUsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('gics1', models.CharField(max_length=100)),
                ('gics2', models.CharField(max_length=100)),
                ('indices', models.CharField(max_length=50)),
            ],
        ),
    ]
