# Generated by Django 4.1.3 on 2024-08-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdaily', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockuslist',
            name='ak_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockuslist',
            name='status',
            field=models.CharField(default='new', max_length=100),
        ),
        migrations.AlterField(
            model_name='stockhklist',
            name='ak_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockhklist',
            name='status',
            field=models.CharField(default='new', max_length=100),
        ),
    ]
