# Generated by Django 4.1.3 on 2024-08-07 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockdaily', '0002_hkqfqdaily_usqfqdaily_delete_stockdailyprices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HKQfqDaily',
            new_name='HKDailyPrices',
        ),
        migrations.RenameModel(
            old_name='USQfqDaily',
            new_name='USDailyPrices',
        ),
    ]
