# Generated by Django 4.1.3 on 2024-08-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdaily', '0002_stockuslist_ak_code_stockuslist_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhklist',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockuslist',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
