# Generated by Django 4.1.3 on 2024-08-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdaily', '0003_alter_stockhklist_status_alter_stockuslist_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HkSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('trade_date', models.DateField()),
                ('signal_name', models.CharField(max_length=40)),
                ('future_high', models.FloatField(null=True)),
                ('increase_days', models.FloatField(null=True)),
                ('increase_pct', models.FloatField(null=True)),
                ('turn_period', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UsSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('trade_date', models.DateField()),
                ('signal_name', models.CharField(max_length=40)),
                ('future_high', models.FloatField(null=True)),
                ('increase_days', models.FloatField(null=True)),
                ('increase_pct', models.FloatField(null=True)),
                ('turn_period', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddConstraint(
            model_name='ussignal',
            constraint=models.UniqueConstraint(fields=('code', 'trade_date', 'signal_name'), name='us_sig_code_date'),
        ),
        migrations.AddConstraint(
            model_name='hksignal',
            constraint=models.UniqueConstraint(fields=('code', 'trade_date', 'signal_name'), name='hk_sig_code_date'),
        ),
    ]
