# Generated by Django 4.1.3 on 2024-08-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdaily', '0003_rename_hkqfqdaily_hkdailyprices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HkQfqFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('factor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UsQfqFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('factor', models.FloatField()),
            ],
        ),
    ]
