# Generated by Django 4.1.3 on 2024-08-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdaily', '0004_hkqfqfactor_usqfqfactor'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hkdailyprices',
            constraint=models.UniqueConstraint(fields=('code', 'trade_date'), name='hk_day_price_code_date'),
        ),
        migrations.AddConstraint(
            model_name='hkqfqfactor',
            constraint=models.UniqueConstraint(fields=('code', 'start_date'), name='hk_qfq_code_date'),
        ),
    ]
