# Generated by Django 4.1.3 on 2024-08-11 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockdaily', '0004_hksignal_ussignal_ussignal_us_sig_code_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hksignal',
            old_name='future_high',
            new_name='chg_pct_10d',
        ),
        migrations.RenameField(
            model_name='hksignal',
            old_name='increase_days',
            new_name='chg_pct_20d',
        ),
        migrations.RenameField(
            model_name='hksignal',
            old_name='increase_pct',
            new_name='chg_pct_5d',
        ),
        migrations.RemoveField(
            model_name='hksignal',
            name='turn_period',
        ),
    ]
