# Generated by Django 4.1.3 on 2024-08-12 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockdaily', '0005_rename_future_high_hksignal_chg_pct_10d_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ussignal',
            old_name='future_high',
            new_name='chg_pct_10d',
        ),
        migrations.RenameField(
            model_name='ussignal',
            old_name='increase_days',
            new_name='chg_pct_20d',
        ),
        migrations.RenameField(
            model_name='ussignal',
            old_name='increase_pct',
            new_name='chg_pct_5d',
        ),
        migrations.RemoveField(
            model_name='ussignal',
            name='turn_period',
        ),
    ]
