# Generated by Django 4.1.3 on 2024-08-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockdaily', '0005_hkdailyprices_hk_day_price_code_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hkqfqfactor',
            old_name='start_date',
            new_name='trade_date',
        ),
    ]
