# Generated by Django 4.1.3 on 2024-08-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdaily', '0006_rename_start_date_hkqfqfactor_trade_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hkqfqfactor',
            name='hk_qfq_code_date',
        ),
        migrations.AddConstraint(
            model_name='hkqfqfactor',
            constraint=models.UniqueConstraint(fields=('code', 'trade_date'), name='hk_qfq_code_date'),
        ),
    ]
