# Generated by Django 4.1.3 on 2024-08-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockdaily', '0007_remove_hkqfqfactor_hk_qfq_code_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usqfqfactor',
            old_name='start_date',
            new_name='trade_date',
        ),
        migrations.RemoveField(
            model_name='usdailyprices',
            name='fq_type',
        ),
        migrations.AddField(
            model_name='stockhklist',
            name='status',
            field=models.CharField(default='normal', max_length=100),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='usdailyprices',
            constraint=models.UniqueConstraint(fields=('code', 'trade_date'), name='us_day_price_code_date'),
        ),
        migrations.AddConstraint(
            model_name='usqfqfactor',
            constraint=models.UniqueConstraint(fields=('code', 'trade_date'), name='us_qfq_code_date'),
        ),
    ]
